name: CI CD

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: CI=false npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
